#!/usr/bin/env bash

set -e
set -u

TMPDIR=${TMPDIR:=/tmp}
test -d $TMPDIR

AP_BRANCH=${AP_BRANCH:=master}
AP_FILES=${AP_FILES:=.}
AP_CMD=${AP_CMD:=make update}

REPO_URL="https://${GH_USER}:${GH_TOKEN}@github.com/${AP_REPO}.git"
CREATE_PR_URL="https://api.github.com/repos/${AP_REPO}/pulls"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BRANCH="autopull/${AP_BRANCH}/$(date -u +%Y-%m-%dT%H-%M-%SZ)"
DIR="${TMPDIR}/autopull/${DATE}"
REPO_DIR="${DIR}/${AP_REPO}"
LOG="${DIR}/cmd.log"
JSON="${DIR}/pull-request.JSONson"

echo "Repository: $AP_REPO"
echo "Branch:     $AP_BRANCH"
echo "Files:      $AP_FILES"
echo "Command:    $AP_CMD"
echo "User:       $GH_USER"

git clone $REPO_URL $REPO_DIR
(
cd $REPO_DIR
git checkout $AP_BRANCH
git checkout -q -b $BRANCH
$AP_CMD 2>&1 > $LOG
LOG_DATA=`cat $LOG`
git add $AP_FILES
git commit -m "$(echo "autopull: ${DATE}\n\n${AP_CMD}\n\n${LOG_DATA}")"
git push origin $BRANCH:$BRANCH

PR=$(cat <<EOF
{
  "title": "autopull: $DATE",
  "base": "$AP_BRANCH",
  "head": "$BRANCH"
}
EOF)

curl -sS -i \
--header "Authorization: token ${GH_TOKEN}" \
--data "${PR}" \
--request POST ${CREATE_PR_URL} > $JSON

grep -q "201 Created" $JSON || (cat $JSON && exit 1)
API_URL=$(grep -A1 '"self": {' $JSON | grep href | cut -f 2- -d ':' | cut -f 2 -d '"')
PULL_ID=$(echo $API_URL | cut -f 8- -d / )
PR_URL="https://github.com/${AP_REPO}/pull/${PULL_ID}"
echo "Created pull request $PULL_ID: $PR_URL"
)
